version: '3.7'

networks:
  internal:
    driver: bridge

volumes:
  mongo-simplechat_volume:
    driver: local

services:
  nginx-proxy:
    container_name: nginx-proxy
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - internal

  node-simplechat:
    container_name: node-simplechat
    image: luanleiteti/simple-chat:v4
    environment:
      - VIRTUAL_HOST=simplechat.local
      - VIRTUAL_PORT=3000
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_DATABASE=${MONGO_DATABASE}
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
    networks:
      - internal
    restart: on-failure
    depends_on: 
      - mongo-simplechat
    expose:
      - "3000"
  
  mongo-simplechat:
    container_name: mongo-simplechat
    image: mongo:5.0.5
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - internal
    volumes:
      - mongo-simplechat_volume:/data/db
    expose:
      - "27017"
